Core Linux System Logs
[monitor:///var/log/syslog]
disabled = 0
index = main
sourcetype = syslog

Authentication and SSH Logs
[monitor:///var/log/auth.log]
disabled = 0
index = main
sourcetype = linux_secure

KVM / Virtual Machine Logs
[monitor:///var/log/libvirt/qemu/]
disabled = 0
index = main
sourcetype = kvm_qemu